title: "Gabriele Dell'Orto"
email: "gabriele.dellorto95@gmail.com"
description: "Food-4-Thoughts"
baseurl: ""            # leave empty for username.github.io
url: "https://gabrieledello.github.io"
#header_image: /assets/img/Homepage-cover.jpg

plugins:
  - jekyll-remote-theme

remote_theme: "StartBootstrap/startbootstrap-clean-blog-jekyll"

author:
  name: "Gabriele Dell'Orto"

github_username: "gabrieledello"

nav_links:
  - title: "Home"
    url: /
  - title: "About"
    url: /about
  - title: "Posts"
    url: /posts
  - title: "Contact"
    url: /contact
