title: "Gabriele Dell'Orto"
description: "Dr. in BioMechanical engineering, researching vehicle dynamics, tyre mechanics, comfort, and vibration."
header_image: "/assets/img/Homepage-cover.jpg"

baseurl: ""            # leave empty for username.github.io
url: "https://gabrieledello.github.io"

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

remote_theme: "StartBootstrap/startbootstrap-clean-blog-jekyll"

author:
  name: "Gabriele Dell'Orto"

github_username: "gabrieledello"

nav_links:
  - title: "Home"
    url: /
  - title: "About"
    url: /about
  - title: "Posts"
    url: /posts
  - title: "Contact"
    url: /contact
